# Generated by Django 4.0.4 on 2022-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('link', models.CharField(max_length=250)),
                ('nota_minima', models.FloatField()),
            ],
        ),
    ]
