# Generated by Django 4.0.4 on 2022-05-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_conteudo_id_curso_conteudo_nota_minima'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursos',
            name='nota_minima',
        ),
        migrations.AddField(
            model_name='recursos',
            name='id_conteudo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conteudo.conteudo'),
            preserve_default=False,
        ),
    ]
