# Generated by Django 4.0.4 on 2022-05-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_tempo_duracao'),
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='id_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='nota_minima',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
