# Generated by Django 4.0.4 on 2022-05-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='tempo_duracao',
            field=models.FloatField(),
        ),
    ]
